apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 3tier-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sadanand25/3tieristo.git
    targetRevision: main
    path: overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true