apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - frontend/deployment.yaml
  - backend/deployment.yaml
  - backend/configmap.yaml
  - database/postgres.yaml
  - database/mysql.yaml
  - database/redis.yaml
  